local module = {}

module.HD_UNLOCK_ID.STARTER1 = 1
module.HD_UNLOCK_ID.STARTER2 = 2
module.HD_UNLOCK_ID.STARTER3 = 3
module.HD_UNLOCK_ID.STARTER4 = 4
module.HD_UNLOCK_ID.AREA_RAND1 = 5
module.HD_UNLOCK_ID.AREA_RAND2 = 6
module.HD_UNLOCK_ID.AREA_RAND3 = 7
module.HD_UNLOCK_ID.AREA_RAND4 = 8
module.HD_UNLOCK_ID.OLMEC_WIN = 9
module.HD_UNLOCK_ID.WORM = 10
module.HD_UNLOCK_ID.SPIDERLAIR = 11
module.HD_UNLOCK_ID.YETIKINGDOM = 12
module.HD_UNLOCK_ID.HAUNTEDCASTLE = 13
module.HD_UNLOCK_ID.YAMA = 14
module.HD_UNLOCK_ID.OLMEC_CHAMBER = 15
module.HD_UNLOCK_ID.TIKIVILLAGE = 16
module.HD_UNLOCK_ID.BLACKMARKET = 17
module.HD_UNLOCK_ID.RUSHING_WATER = 18
module.HD_UNLOCK_ID.MOTHERSHIP = 19
module.HD_UNLOCK_ID.COG = 20

return module